#!/bin/sh

[[ $- != *i* ]] && return

[[ -s /etc/bashrc ]] && . /etc/bashrc
[[ -s ~/.config/sh/alias ]] && . ~/.config/sh/alias

shopt -s histappend
shopt -s checkwinsize
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
